### PR TITLE
Manipulator fixing

### PR DESCRIPTION
**Pull request by jastronaut**

### CODE REVIEW

**Comment by amycontreras** [comment]
NICE

**Comment by jastronaut** [comment]
NICE!!

**Comment by blast-hardcheese** [comment]
These can't be automatically merged, but if you:

```
git checkout manipulatorFixing
git fetch
git merge --no-ff master
git mergetool
```

it'll let you manually merge. If you get in the habit of keeping PRs small (and localized to the functions you're working in) this won't be an issue.

```
int foo() {
    return 5;
}

void bar() {
    cout << "Hey!" << endl;
}
```

If we have two pull requests,

```
-    return 5;
+    return 6;
```

and

```
-    cout << "Hey!" << endl;
+    cout << "Hey again!" << endl;
```

these won't conflict at all. It takes some work, but it is worth it.

**Comment by blast-hardcheese** [comment]
~~[pr-5.mp4](http://blast.hardchee.se/~/files/2015-02-03/pr-5.mp4) is a screen recording of resolving this merge commit. (Sorry the window size was so small!)~~
[pr-5-2.mp4](http://blast.hardchee.se/~/files/2015-02-03/pr-5-2.mp4) is a more thorough screen recording resolving this merge commit. Also, I made the screen bigger.

**Pull request closed without merging**
